# version: '3.8'

services:
  api:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
